import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";
import React, { ReactNode } from "react";
import Navigationbar from "@/components/NavigationBar";
// import Provider from "@/context/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) return <html></html>;

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-200 flex  flex flex-col items-center py-4">
          <Link
            className="mx-2 p-4 font-semibold hover:text-gray-600"
            href={"/"}
          >
            Home
          </Link>
          <Navigationbar/>
          {children}
        </header>
      </body>
    </html>
  );
}
